18F/identity-cookbooks

identity_shared_attributes/.gitignore
identity_shared_attributes/README.md
identity_shared_attributes/attributes/default.rb
identity_shared_attributes/chefignore
identity_shared_attributes/metadata.rb

I tested this by running the IDP and PIV/CAC Kitchen tests from [this branch](https://github.com/18F/identity-devops/compare/mark-from-usds/identity_shared_attributes01?expand=1).

Create identity_shared_attributes for things that span recipes/repos

---

passenger/templates/default/nginx.conf.erb

Currently we're receiving many alerts in #identity-events for exceeding this limit but we are not observing any DoS or degradation with login.gov.  Will increase the connection rate limit to a higher setting.

Increase connection rate limit to 20 request per 5 minutes

---

identity_base_config/metadata.rb
identity_base_config/recipes/ruby.rb
identity_shared_attributes/attributes/default.rb
passenger/recipes/daemon.rb
passenger/recipes/install.rb

Add proxy_server (i.e. the proxy without the https:// or the port), proxy_port, and rbenv_root to identity_shared attributes and use them when possible.
Since this is across repos, you can see the exact changes I made to the version in identity-devops in [this commit](https://github.com/18F/identity-cookbooks/commit/3761691bcb7b31bea03c7d79b099f997bb81d1a1).

Move login_dot_gov::ruby into identity_base_config

---

passenger/files/default/compile-passenger-module

This is usually about 4,400 files -- way too noisy to be printing to the
log for no reason. We really just want to know if the passenger gem
could be found.

Print count of passenger files, not whole listing.

---

passenger/attributes/daemon.rb
passenger/metadata.json
passenger/recipes/daemon.rb
passenger/templates/default/nginx.conf.erb

__Why__
We do not want process scaling enabled on a host that only serves a single app. See: https://www.phusionpassenger.com/library/config/nginx/optimization/#minimizing-process-spawning
Fixes: 18F/identity-devops#1431
In summary this PR:
- Disables dynamic scaling in Passenger and fixes the max process counts to 2x cpu count
- Further organizes default attributes used by the Passenger cookbook
- Adds a default config for nginx worker_processes directive and sets default to cpu count as recommended by http://nginx.org/en/docs/ngx_core_module.html#worker_processes
- Removes hardcoded value for worker_processes and adds variable to nginx conf template
- Configures Passenger Nginx module to only compile support for Ruby
- Fixes error with passenger_pre_start directive being located outside …

Passenger config fixes and optimizations

---

cloudhsm/metadata.rb

This is needed for https://github.com/18F/identity-devops/issues/1561

cloudhsm: Add missing dependency on cloudhsm SDK.

---

identity_base_config/files/default/id-asg-skip-abandon-hook
identity_base_config/metadata.rb
identity_base_config/recipes/default.rb

When troubleshooting issues with instance provisioning, it is often
useful to keep an instance around for inspection. We have a flag file
that we can drop in /etc/login.gov/info/ that instructs provision.sh not
to complete the ASG lifecycle hook with ABANDON in the event that
provisioning fails.
But it's hard to remember this filename when you're racing the clock to
save the instance.
Add a new script, `id-asg-skip-abandon-hook`, that knows the name of
this file and will create it for you.

Add a helper script to skip the ASG abandon hook.

---

identity_fips_openssl/attributes/default.rb

At some point during my work on 18F/identity-devops#1811, `identity_fips_openssl` was moved here and out of the `identity-base-image` repo. Somehow my branch never tripped over these changes, nor found conflicts, so the checksum update for OpenSSL-1.0.2t didn't make its way over to this repo. This PR fixes that.

fixing checksum for OpenSSL-1.0.2t tarball as it got lost in the shuffle

---

identity_ossec/metadata.rb
identity_ossec/recipes/default.rb

Rather than compile `ossec` from source, removes the `atomicorp` repo from `/etc/apt/sources.list.d/` after `ossec` installation has completed. Since this is done in the base image, hosts should no longer break if `atomicorp` is serving up 404s.
Fixes #1856.

remove updates.atomicorp.com repository after installing ossec

---

passenger/attributes/daemon.rb
passenger/recipes/daemon.rb

Fixes https://github.com/18F/identity-devops/issues/1294
Upgrades to the [latest passenger](https://github.com/phusion/passenger/releases) (6.0.4) and adds a step to compile the passenger agent binary in the recipe.
```
ubuntu@idp-i-0367a93e84daef2d4:~$ passenger-config compile-agent -h
Usage: passenger-config compile-agent [OPTIONS]
Compile the Phusion Passenger agent binary. The agent binary is required for
Phusion Passenger to function properly.
Options:
--working-dir PATH           Store temporary files in the given
directory, instead of creating one
--auto                       Run in non-interactive mode. Default when
stdin or stdout is not a TTY
--optimize                   Compile agent with optimizations
-f, --force                      Skip sanity checks
--no-force-tip …
```

Upgrade to latest Passenger (6.0.4)

---

passenger/attributes/daemon.rb
passenger/metadata.json

Passing `--with-openssl` to Passenger results in a new build of OpenSSL, without the configured defaults.  This patch tells the build to link against the existing, correctly built OpenSSL instead, saving 1 extra and misconfigured rebuild, restoring FIPS compliance.
```
root@idp-i-01b462.sjh:~# /opt/nginx/sbin/nginx -V
nginx version: nginx/1.17.3
built by gcc 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04)
built with OpenSSL 1.0.2t-fips  10 Sep 2019 (running with OpenSSL 1.0.2n  7 Dec 2017)
TLS SNI support enabled
configure arguments: --prefix=/opt/nginx --with-http_ssl_module --with-http_v2_module --with-http_realip_module --with-http_gzip_static_module --with-http_stub_status_module --with-http_addition_module --with-cc-opt=-Wno-error --with-ld-opt= …
```

Build nginx with fips

---

identity_ruby/metadata.rb

Ruby build fails with OpenSSL on versions after 1.3.  Force berks to install only 1.2 version.

Force ruby_build to 1.2 version

---

passenger/templates/default/nginx.conf.erb

- nginx: [warn] duplicate MIME type text/html in /opt/nginx/conf/nginx.conf:28
- http://nginx.org/en/docs/http/ngx_http_gzip_module.html
- gzip_types: Response with text/html type are always compressed

Resolves duplicate MIME warnings

---

identity_ossec/files/default/syslog_rules.xml
identity_ossec/recipes/default.rb

After `ossec` is installed/configured via the `ossec` cookbook (in `identity_ossec`), override the default `syslog_rules.xml` with a custom one built here, which removes alerting on Rule 1003 (RFC5424) for syslog messages >2048 bytes in length.
Addresses https://github.com/18F/identity-devops/issues/2562

temporary syslog_rules override to prevent ossec alerts from nginx's access.log

---

identity_ossec/files/default/syslog_rules.xml
passenger/templates/default/nginx.conf.erb

Addresses https://github.com/18F/identity-devops/issues/2566
* Removes cookie log from `/var/log/nginx/access.log` for improved security and shorter log lines
* Keeps `syslog_rules.xml` override but adds slightly longer max log line limit matching the RFC "SHOULD" recommended minimum of 2048 bytes per line 
* Tested `base` and `rails` AMI builds - Working (see bottom)
* Sample `access.log` line WITHOUT cookies:
~~~
hostname="idp.pauldoom.identitysandbox.gov" dest_port="443" dest_ip="172.16.33.141" src="98.240.210.150" src_ip="172.16.33.228" lb_if_proxied="172.16.33.228" user="-" time_local="16/Jun/2020:04:25:41 +0000" protocol="HTTP/1.1" status="200" bytes_out="0" bytes_in="0" http_referer="https://idp.pauldoom.identitysandbox.gov/account" http_user_agent="Mozilla/5.0 (Macintosh; Intel …

Stop NGINX cookie logging and enable longer syslog limit rule in OSSEC

---

identity_ossec/files/default/syslog_rules.xml

The longer limit (2048 instead of 1023 bytes) still triggers on some messages
from SSM Agent and NGINX.  After review we did not find cases where the lines
triggering the warning were actually passing through `syslogd`.   Our SSP
states use of CloudWatch Logs and ELK (with logs ingested by FileBeat), neither
of which will truncate these longer messages.
This PR disables the rule permanently.
See https://gsa-tts.slack.com/archives/C16RSBG49/p1593011646479700 for context.
Test run from IdP instance:
~~~
curl -k https://127.0.0.1/?thisisthequerythatneverendsthisisthequerythatneverendsthisisthequerythatneverendsthisisthequerythatneverendsthisisthequerythatneverendsthisisthequerythatneverendsthisisthequerythatneverendsthisisthequerythatneverendsthisisthequerythatneverendsthisisthequerythatnever …

Turn off syslog_rules.xml rule 1003

---

passenger/Berksfile.lock

One Berksfile update:
* identity_shared_attributes 0.1.0 -> 0.1.2
Change tested with new Base and Rails images

Update All The Things 2020-07-08

---

identity_base_config/recipes/ruby.rb

Add New Relic endpoints env variables to /etc/environment as a backstop.

Add NewRelic endpoints to environment

---

passenger/attributes/daemon.rb

Passenger to 6.0.6
This will update nginx to 1.18.0
Issue https://github.com/18F/identity-security-private/issues/1778

Upgrade passenger version

---

identity_fips_openssl/recipes/default.rb
identity_ruby/recipes/default.rb
passenger/attributes/daemon.rb
passenger/files/default/fipsmode.patch
passenger/recipes/daemon.rb

I tested this by applying it by hand.  I will investigate the build process and see if I can get an AMI out of this that I can try in my tspencer env, but for now, I thought I'd put this out for people to comment on.
We appear to be using a FIPS-certified module, but FIPS_mode has not been set.  This turns that on for nginx/passenger

add fips mode to nginx/passenger

---

identity_ossec/files/default/syslog_rules.xml

roll back alerting on cgroup OOM killer until we can get an operational alert going

adjust OSSEC alerting

---

passenger/metadata.json
passenger/templates/default/nginx.conf.erb

By default Passenger log messages are written to the Nginx global error log: https://www.phusionpassenger.com/library/config/nginx/reference/#passenger_log_file. This change has passenger log to a separate file for its events. This will make it easier to parse log events and debug issues with our stack.
Note, this also refactors the config block so its alphabetized and is spaced in a more human friendly fashion similar to terraform.

Log passenger errors to a separate file

---

passenger/attributes/daemon.rb
passenger/templates/default/nginx.conf.erb

This adds config that increases the nofile limit (https://wiki.archlinux.org/index.php/Limits.conf#nofile) for the passenger (rails) and nginx worker process (anything not handled by rails) in support of https://github.com/18F/identity-devops/issues/3152. The value of 2x the worker connections was chosen since each worker connection, in general, needs two open files in order to function correctly. 
I tested by creating a new base image using this PR's SHA for the cookbooks:
```
amazon-ebs:     +worker_rlimit_nofile 2048;
amazon-ebs:     +pid /var/run/nginx.pid;
amazon-ebs:
amazon-ebs:     -#error_log  logs/error.log;
amazon-ebs:     -#error_log  logs/error.log  notice;
amazon-ebs:     -#error_log  logs/error.log  info;
amazon-ebs:     -
amazon-ebs:     -#pid        logs/nginx.pid; …
```

Set nofile limit to 2x the # of worker connections

---

passenger/attributes/daemon.rb
passenger/templates/default/nginx.conf.erb

Addresses https://github.com/18F/identity-devops/issues/3543
* Changes `/var/log/nginx/access.log` to JSON line format
* Adds flag to disable ALB relevant headers for NLB/ELB TCP load balancers
* Adds flag to add SSL client certificate attributes for PIVCAC use
* Removes unused fancy log
Example snippet of `/opt/nginx/conf/nginx.conf`:
~~~
log_format kv escape=json
'{'
'"time": "$time_local", '
'"hostname": "$host", '
'"dest_port": "$server_port", '
'"dest_ip": "$server_addr", '
'"src": "$remote_addr", '
'"src_ip": "$realip_remote_addr", '
'"user": "$remote_user", '
'"protocol": "$server_protocol", '
'"http_method": "$request_method", '
'"status": "$status", '
'"bytes_out": "$body_bytes_sent", '
'"bytes_in": "$upstream_response_length", '
'"http_referer": "$http_referer", ' …

Change NGINX access.log to JSON line structured format

---

passenger/attributes/daemon.rb

Addresses https://github.com/18F/identity-security-private/issues/2400
NGINX 1.20.1 - Fixes CVE-2021-23017
Passenger 6.0.9 - Aligns with NGINX 1.20.1

Upgrade NGINX to 1.20.1 and Passenger to 6.0.9

---

identity_base_config/recipes/ruby.rb

This particular execution block is failing -- notably, on `pivcac` and `worker` instances.
```
---- Begin output of systemctl restart snapd ----
STDOUT: 
STDERR: Job for snapd.service canceled.
---- End output of systemctl restart snapd ----
Ran systemctl restart snapd returned 1
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
provision.sh: ERROR -- exiting after failure
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
```
While a root cause hasn't yet been determined -- likely another issue with the upstream Ubuntu Pro images -- this block is actually no longer needed, so it can be removed to prevent the above crash from happening.

removing snapd restart from identity_base_config::ruby

---

config_loader/Berksfile
config_loader/attributes/default.rb
config_loader/libraries/config_helper.rb
config_loader/metadata.rb

Citadel is unmaintained and our use of it is limited to copying files from S3, which we can do ourselves and reduce the amount of code we depend on
I tested this in my sandbox, and files seem to be copied correctly

Remove Citadel

---

identity_ruby/attributes/default.rb
identity_ruby/recipes/default.rb
identity_shared_attributes/attributes/default.rb

The `identity_ruby` recipe currently grabs the most recent version of Bundler when `gem install bundler` is run. At the moment, [said most-recent-version (2.3.12) has an open bug related to the `required_rubygems_version` field](https://github.com/rubygems/rubygems/issues/5492), causing most/all `bundle install` operations with v2.3.12 to fail with `undefined method 'none?' for nil:NilClass` errors.
This PR updates the `identity_ruby` recipe so that the version of Bundler can be specified via the `default['identity_ruby']['bundler_version']` attribute, which we can pass in via another cookbook/recipe that calls it (hence defaulting to `nil` by default here).

specify bundler version via identity_ruby attribute

---

aws_metadata/libraries/aws_metadata.rb

**Multi CIDR Block Support**
This PR expands the functionality of aws_metadata library to support multiple CIDR blocks assigned to a single VPC instance.

Multi CIDR Block Support

---

static_eip/resources/assign.rb

Occasionally, the baked-into-the-AMI package of `python-pip-whl` will be out of date and/or requiring a specific hard-coded version. As a result, `python3-pip` -- which has `python-pip-whl` as a dependency -- will fail to install:
```
STDOUT: Reading package lists...
Building dependency tree...
Reading state information...
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation: 
The following packages have unmet dependencies:
python3-pip : Depends: python-pip-whl (= 9.0.1-2.3~ubuntu1.18.04.5) but 9.0.1-2.3~ubuntu1.18.04.5+esm2 is to be installed
Recommends: …
```

remove pip-whl before doing a python3-pip install

---

passenger/attributes/daemon.rb
passenger/recipes/daemon.rb
passenger/templates/default/nginx.conf.erb

* Drops the already busted local VPC calculation and just uses the
three RFC1918 blocks plus the carrier NAT space to the list of
ranges not to consider in figuring out the source IP from X-Forwarded-For
* Adds support for CloudFront's IPv6 ranges for when we turn on v6

Add all private IPv4 space to CIDRs to be ingnored in source IP calculation

---

passenger/attributes/daemon.rb
passenger/templates/default/nginx.conf.erb

Logs the following headers to `/var/log/nginx/access.log` being populated by CloudFront as of Requires https://github.com/18F/identity-devops/pull/5075
* `CloudFront-Viewer-Address`  -> `http_cloudfront_viewer_address` : Source IP and port for client connection to CloudFront
* `CloudFront-Viewer-Http-Version` -> `http_cloudfront_viewer_http_version` : HTTP version used for client connection to CloudFront
* `CloudFront-Viewer-TLS` ->  `http_cloudfront_viewer_tls` : TLS version and ciphers used for client connection to CloudFront
* `CloudFront-Viewer-Country` -> `http_cloudfront_viewer_country` : ISO country code for IP client used to connect
* `CloudFront-Viewer-Country-Region` -> `http_cloudfront_viewer_country_region` : ISO region subcode for IP client used to connect
Sample log output: …

Add custom CloudWatch headers to NGINX access logs

---

passenger/attributes/daemon.rb
passenger/metadata.json
passenger/recipes/daemon.rb
passenger/templates/default/nginx.conf.erb

This adds the headers_more module so we can override the forced headers added by passenger (and nginx?). It's easy to set a variable for the `Server` header if we ever want to do something fun with that.
Build completes and generates AMI
```
amazon-ebs.ubuntu-pro:   * remote_file[/opt/nginx/src/headers-more-nginx-module-0.34.tar.gz] action create	
amazon-ebs.ubuntu-pro:     - create new file /opt/nginx/src/headers-more-nginx-module-0.34.tar.gz	
amazon-ebs.ubuntu-pro:     - update content in file /opt/nginx/src/headers-more-nginx-module-0.34.tar.gz from none to 0c0d2c	
amazon-ebs.ubuntu-pro:     (new content is binary, diff output suppressed)	
amazon-ebs.ubuntu-pro:   * execute[tar xzvf /opt/nginx/src/headers-more-nginx-module-0.34.tar.gz -C /opt/nginx/src] action run …
```

Add headers_more module to nginx and remove server/x-powered-by

---

passenger/templates/default/nginx.conf.erb

Adds a little more info to help remove unused or weak ciphers.
Sample log line after change on `idp`:
~~~json
{
"time": "20/Jan/2023:06:24:05 +0000",
"hostname": "x.x.x.x",
"dest_port": "443",
"dest_ip": "y.y.y.y",
"src": "z.z.z.z",
"src_ip": "z.z.z.z",
"user": "",
"protocol": "HTTP/1.1",
"http_method": "GET",
"status": "200",
"bytes_out": "129",
"bytes_in": "139",
"http_referer": "",
"http_user_agent": "ELB-HealthChecker/2.0",
"nginx_version": "1.22.0",
"http_cloudfront_viewer_address": "",
"http_cloudfront_viewer_http_version": "",
"http_cloudfront_viewer_tls": "",
"http_cloudfront_viewer_country": "",
"http_cloudfront_viewer_country_region": "",
"http_x_forwarded_for": "",
"http_x_amzn_trace_id": "",
"response_time": "0.105",
"request_time": "0.106",
"request": "GET /api/health …

Log TLS protocol and version in NGINX logs

---

passenger/attributes/daemon.rb

https://github.com/phusion/passenger/releases/tag/release-6.0.17
> Upgrades preferred Nginx to 1.22.1 from 1.20.2.
Upgrades passenger to the latest stable version and ditto for nginx.

Update passenger and nginx to latest stable releases

---

passenger/attributes/daemon.rb
passenger/templates/default/nginx.conf.erb

The title says it all. This is important since the default of 100 seems more reasonable for CPU-bound apps, which we are not, ATM at least.

Make passenger request queue size configurable

---

config_loader/libraries/config_helper.rb

* Adds the `app` flag to ConfigLoader which instructs it to load the application instead of platform level secret
* Fixes `load_config_or_nil` to pass through flags to `load_config`

Add optional app flag to ConfigLoader to use an alternate secret bucket
